version: "3"

tasks:
  default:
    aliases: [apply]
    deps:
      - tfinit
    cmds:
      # - terraform init
      # - terraform apply -auto-approve -target azurerm_container_registry.main -refresh=false
      - terraform apply -auto-approve 

    generates:
      - .terraform.lock.hcl


  tfinit:
    cmds:
      - terraform init
    sources:
      - docker.tf
      - ehclient_deployment.tf
      - fedid_sa.tf
      - locals.tf
      - main.tf
      - outputs.tf
      - publisher_deployment.tf
      - rbac_main.tf
      - rbac_secondary.tf
      - storageaccounts.tf
      - subscriber_deployment.tf
      - variables.tf
    generates:
      - .terraform.lock.hcl
  
  clean:
    cmds:
      - terraform destroy -auto-approve -refresh=false
      - rm -f .env

  kill:
    cmds:
      - rm -f terraform.tfstate terraform.tfstate.backup .terraform.lock.hcl
  # tokenfile:
  #   cmds:
  #     - |
  #       sleep 10 &&  ## a better way is to query that this is running or trap and retry whole block
  #       POD_NAME=$(kubectl get pods -n aadwi -l app=ehclient -o jsonpath='{.items[0].metadata.name}') && 
  #       echo $POD_NAME &&
  #       kubectl exec -n aadwi $POD_NAME -- sh -c 'tar -czf - -h /var/run/secrets/azure/tokens/azure-identity-token' > local-file.tar.gz
  #     - tar -xzf local-file.tar.gz && rm local-file.tar.gz

  ehclient:
    cmds:
      - terraform taint null_resource.mvn_package_demo_app_ehclient
      - terraform taint docker_image.demo_app_ehclient
      - terraform taint kubernetes_deployment.ehclient
      - terraform apply -auto-approve 
      #-target null_resource.mvn_package_demo_app_ehclient -target docker_image.demo_app_ehclient -target kubernetes_deployment.ehclient