# https://taskfile.dev

version: "3"

includes:
  aks: ./aks/Taskfile.yml
  apps: ./apps/Taskfile.yml

tasks:
  default:
    summary: runs terraform apply for all sub terraform projects
    dotenv: ['.env', '.envrc.']
    deps:
      - checkenv
    aliases:
      - "apply"
    cmds:
      - terragrunt run-all apply -auto-approve --terragrunt-non-interactive --terragrunt-debug --terragrunt-log-level debug
    silent: false


  checkenv:
    silent: true
    dotenv: ['.env', '.envrc.']
    cmds:
      - |
        # List the environment variables you want to check
        variables=("demo_tenant_id" "demo_subscription_id" "demo_tenant_id2" "demo_subscription_id2")
        for var in "${variables[@]}"
        do
          if [[ -z "${!var}" ]]; then
            echo -e "\033[31mERROR:\033[0m Environment variable \033[33m $var \033[0m is not set"
            for var in "${variables[@]}"
            do
              echo -e "\033[33m $var \033[0m = ${!var}"
            done
            exit 1
          fi
        done
        echo "All variables are set"

  verify:
    cmds:
      - task check
    deps:
      - creds

  creds:
    dir: ./aks
    cmds:
      - task creds
 
  check:
    dir: ./apps
    cmds:
      - task check

  clean:
    cmds:
      - task aks:clean
      - task apps:clean

  killfiles:
    desc: Removes various state files and caches
    cmds:
      - rm -f terraform.tfstate
      - rm -rf aks/.terraform aks/.terragrunt-cache aks/.env aks/.terraform.lock.hcl aks/.task aks/terragrunt-debug.tfvars.json
      - rm -rf keyvault/.terragrunt-cache keyvault/.terraform.lock.hcl keyvault/terragrunt-debug.tfvars.json
      - rm -rf keyvault2/.terragrunt-cache keyvault2/.terraform.lock.hcl keyvault2/terragrunt-debug.tfvars.json
      - rm -rf apps/.terraform apps/.terragrunt-cache apps/.terraform.lock.hcl apps/terragrunt-debug.tfvars.json apps/.task

  destroy:
    cmds:
      - terragrunt run-all destroy -auto-approve --terragrunt-non-interactive

  kill:
    cmds:
      - az group delete --no-wait -y -n {{.RG1}}
      - az group delete --no-wait -y -n {{.RG2}} --subscription {{.demo_subscription_id2}}
      - az ad app delete --id {{.APP1}}
      # TODO: need cleanup of the Applications
      - task: killfiles
    vars:
      RG1:
        sh: terragrunt output -raw resource_group_name --terragrunt-working-dir ./aks
      RG2:
        sh: terragrunt output -raw resource_group_name --terragrunt-working-dir ./keyvault2
      APP1:
        sh: terragrunt output -raw aad_application_id --terragrunt-working-dir ./apps
    