spring:
  cloud:
    azure:
      eventhubs:
        namespace: testtenant1
        credential:
          managed-identity-enabled: true
        processor:
          checkpoint-store:
            account-name: testb39d
            container-name: testehevents
            account-key: 
          consumer-group: $Default
        event-hub-name: testtenant1eh
    stream:
      bindings:
        produce-out-0:
          destination: testtenant1eh
      poller:
        fixed-delay: 10000  #default is 1sec
    function:
      definition: produce;