spring:
  cloud:
    function:
      definition: publish1;
    stream:
      bindings:
        publish1-out-0:
          destination:
      binders:
        eventhub-1:
          type: eventhubs
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    producer:
                      profile:
                        tenant-id:
                    event-hub-name:
                    namespace:
                    credential:
                      managed-identity-enabled: true
                      client-id:
                    profile:
                      tenant-id:
                    consumer-group: $Default
                    processor:
                      checkpoint-store:
                        credential:
                          managed-identity-enabled: true
                          client-id:
                        profile:
                          tenant-id:
                        endpoint:
                        container-name:
                        account-name:

      poller:
        initial-delay: 0
        fixed-delay: 2000 #default is 1s
