spring:
  cloud:
    azure:
      eventhubs:
        namespace: ehn-eh-demo-primary-tenant-lftux
        credential:
          managed-identity-enabled: true
        processor:
          checkpoint-store:
            endpoint: https://stehdemoprimarytenant.blob.core.windows.net/eventhubs-binder-sample
            container-name: eventhubs-binder-sample
            account-name: stehdemoprimarytenant
          consumer-group: $Default
        event-hub-name: eventhub1
    function:
      definition: produce;
    stream:
      bindings:
        produce-out-0:
          destination: eventhub1
      default:
        producer:
          errorChannelEnabled: true
      poller:
        fixed-delay: 2000  #default is 1sec
