version: '3'

tasks:
  default:
    aliases: [apply]
    cmds:
      - rm -f .terraform.lock.hcl
      - rm -rf .terragrunt-cache
      - terragrunt apply -auto-approve --terragrunt-non-interactive
      - terragrunt output -raw environment_variable_setup > .env
    sources:
      - terragrunt.hcl
      - providers.tf
      - main.tf
      - k8s.tf
      - variables.tf
      - outputs.tf
    generates:
      - .env

  check:
    silent: true
    cmds:
      - echo "secret1= {{.CMD1}}"
      - echo "secret2= {{.CMD2}}"

    vars:
      CMD1:
        sh: $(terragrunt output -raw print_key_vault_secret_command --terragrunt-no-auto-init)
      CMD2:
        sh: $(terragrunt output -raw print_key_vault_secret_command2 --terragrunt-no-auto-init)
  clean:
    cmds:
      - terragrunt destroy -auto-approve -refresh=false --terragrunt-non-interactive
      - rm -f .env
