spring:
  cloud:
    function:
      definition: consume1;
    stream:
      bindings:
        consume1-in-0:
          destination:
          group: $Default
      eventhubs:
        bindings:
          consume1-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      binders:
        eventhub-1:
          type: eventhubs
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    event-hub-name:
                    namespace:
                    credential:
                      managed-identity-enabled: true
                      client-id:
                    consumer:
                      profile:
                        tenant-id:
                      consumer-group: $Default
                    profile:
                      tenant-id:
                    processor:
                      checkpoint-store:
                        credential:
                          managed-identity-enabled: true
                          client-id:
                        profile:
                          tenant-id:
                        endpoint:
                        container-name:
                        account-name:
      poller:
        initial-delay: 0
        fixed-delay: 2000 #default is 1s
