spring:
  profiles:
    active: local
  cloud:
    azure:
      eventhubs:
        namespace: ehn-eh-demo-primary-tenant-lftux
        processor:
          checkpoint-store:
            endpoint: https://stehdemoprimarytenant.blob.core.windows.net/eventhubs-binder-sample
          consumer-group: $Default
        event-hub-name: eventhub1
    function:
      definition: consume;
    stream:
      bindings:
        consume-in-0:
          destination: eventhub1
          group: $Default
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
#server:
#  port: 8081