spring:
  cloud:
    azure:
      eventhubs:
        namespace: testtenant1
        processor:
          checkpoint-store:
            account-name: testb39d
            container-name: testehevents
            account-key: 
    function:
      definition: consume;
    stream:
      bindings:
        consume-in-0:
          destination: testtenant1eh
          group: $Default
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL